run = {
    "task": "fast",
    "mode": "retrain",
    "profile": "pilot",
    # Paired RoPE/CABLE comparisons use the same three model architectures.
    "models": ["base", "sp_both", "fast_sp_both"],
    "position_encodings": ["rope", "cable"],
    "seed": [41,42,43],
    "device": "cuda",
    "dtype": "bfloat16",
    "jobs_per_gpu": "auto",
    "gpu_scheduler": {
        "max_jobs_per_gpu": 8,
        "utilization_target": 90.0,
        "utilization_samples": 5,
        "memory_reserve_fraction": 0.10,
        "min_memory_reserve_gb": 8.0,
        "memory_safety_factor": 1.35,
        "unprofiled_job_memory_gb": 8.0,
        "fallback_jobs_per_gpu": 4,
        "settle_seconds": 3.0,
        "poll_seconds": 0.2,
    },
    "num_threads": 8,
}

premodel = {
    "default": "pythia410m",
    "auto_blocks_alias": True,
    "cache_dir": None,
    "local_files_only": False,
    "torch_dtype": "auto",
    "attn_implementation": "eager",
    "gradient_checkpointing": True,
    "models": {
        "pythia410m": {
            "hf_id": "EleutherAI/pythia-410m",
            "tokenizer_id": "EleutherAI/pythia-410m",
            "revision": "main",
            "family": "pythia",
            "role": "dev",
            "max_position_embeddings": 2048,
            "full_finetune": True,
        },
        "pythia1b": {
            "hf_id": "EleutherAI/pythia-1b",
            "tokenizer_id": "EleutherAI/pythia-1b",
            "revision": "main",
            "family": "pythia",
            "role": "dev",
            "max_position_embeddings": 2048,
            "full_finetune": True,
        },
        "gemma2_2b": {
            "hf_id": "google/gemma-2-2b",
            "tokenizer_id": "google/gemma-2-2b",
            "revision": "main",
            "family": "gemma2",
            "role": "main",
            "max_position_embeddings": 8192,
            "full_finetune": True,
        },
        "gemma2_9b": {
            "hf_id": "google/gemma-2-9b",
            "tokenizer_id": "google/gemma-2-9b",
            "revision": "main",
            "family": "gemma2",
            "role": "scale",
            "max_position_embeddings": 8192,
            "full_finetune": True,
        },
    },
}

model = {
    "n_layer": 6,
    "n_head": 6,
    "d_model": 384,
    "d_ff": 1536,
    "block_size": 1024,
    "vocab_size": 50257,
    "dropout": 0.0,
    "position_encoding": "rope",
    "cable_fused_sdpa": True,
    "cable_augmented_dims": 8,
}

models = {
    "base": {
        "attn": {"name": "std"},
        "ffn": {"name": "std"},
        "loss": {"name": "ce"},
    },
    "adatre02attn": {
        "attn": {"name": "adaptive_threshold", "relative_threshold": 0.02, "length_scale": 1.0, "keep_self": True, "renorm": True},
        "ffn": {"name": "std"},
        "loss": {"name": "ce"},
    },
    "adatre01attn": {
        "attn": {"name": "adaptive_threshold", "relative_threshold": 0.01, "length_scale": 1.0, "keep_self": True, "renorm": True},
        "ffn": {"name": "std"},
        "loss": {"name": "ce"},
    },
    "adatre05attn": {
        "attn": {"name": "adaptive_threshold", "relative_threshold": 0.05, "length_scale": 1.0, "keep_self": True, "renorm": True},
        "ffn": {"name": "std"},
        "loss": {"name": "ce"},
    },
    "topk32attn": {
        "attn": {"name": "topk", "k": 32},
        "ffn": {"name": "std"},
        "loss": {"name": "ce"},
    },
    "topk64attn": {
        "attn": {"name": "topk", "k": 64},
        "ffn": {"name": "std"},
        "loss": {"name": "ce"},
    },
    "topk128attn": {
        "attn": {"name": "topk", "k": 128},
        "ffn": {"name": "std"},
        "loss": {"name": "ce"},
    },
    "sparse50ffn": {
        "attn": {"name": "std"},
        "ffn": {"name": "sparse", "mode": "topk", "k": 768},
        "loss": {"name": "ce"},
    },
    "sparse25ffn": {
        "attn": {"name": "std"},
        "ffn": {"name": "sparse", "mode": "topk", "k": 384},
        "loss": {"name": "ce"},
    },
    "sparse12ffn": {
        "attn": {"name": "std"},
        "ffn": {"name": "sparse", "mode": "topk", "k": 192},
        "loss": {"name": "ce"},
    },
    "sparse06ffn": {
        "attn": {"name": "std"},
        "ffn": {"name": "sparse", "mode": "topk", "k": 96},
        "loss": {"name": "ce"},
    },
    "fixedmask50ffn": {
        "attn": {"name": "std"},
        "ffn": {"name": "fixed_mask", "k": 768, "mask_seed": 1729, "scale_output": False},
        "loss": {"name": "ce"},
    },
    "fixedmask25ffn": {
        "attn": {"name": "std"},
        "ffn": {"name": "fixed_mask", "k": 384, "mask_seed": 1729, "scale_output": False},
        "loss": {"name": "ce"},
    },
    "fixedmask12ffn": {
        "attn": {"name": "std"},
        "ffn": {"name": "fixed_mask", "k": 192, "mask_seed": 1729, "scale_output": False},
        "loss": {"name": "ce"},
    },
    "groupmix2ffn": {
        "attn": {"name": "std"},
        "ffn": {"name": "groupmix", "groups": 2, "mix_ratio": 0.125, "mix_alpha": 0.25},
        "loss": {"name": "ce"},
    },
    "groupmix4ffn": {
        "attn": {"name": "std"},
        "ffn": {"name": "groupmix", "groups": 4, "mix_ratio": 0.125, "mix_alpha": 0.25},
        "loss": {"name": "ce"},
    },
    "groupmix2pmffn": {
        "attn": {"name": "std"},
        "ffn": {"name": "groupmix", "groups": 2, "mix_d_ff": 768, "mix_alpha": 0.25},
        "loss": {"name": "ce"},
    },
    "groupmix4pmffn": {
        "attn": {"name": "std"},
        "ffn": {"name": "groupmix", "groups": 4, "mix_d_ff": 1152, "mix_alpha": 0.25},
        "loss": {"name": "ce"},
    },
    "structured25ffn": {
        "attn": {"name": "std"},
        "ffn": {"name": "structured_sparse", "groups": 8, "active_groups": 2, "route": "cycle", "scale_output": False},
        "loss": {"name": "ce"},
    },
    "structured50ffn": {
        "attn": {"name": "std"},
        "ffn": {"name": "structured_sparse", "groups": 8, "active_groups": 4, "route": "cycle", "scale_output": False},
        "loss": {"name": "ce"},
    },
    "structured12ffn": {
        "attn": {"name": "std"},
        "ffn": {"name": "structured_sparse", "groups": 8, "active_groups": 1, "route": "cycle", "scale_output": False},
        "loss": {"name": "ce"},
    },
    "sp_attn": {
        "attn": {"name": "sp", "k": 256, "r_ratio": 0.5, "renorm": False},
        "ffn": {"name": "std"},
        "loss": {"name": "ce"},
    },
    "sp_ffn": {
        "attn": {"name": "std"},
        "ffn": {"name": "sp", "k_ratio": 0.08, "r_ratio": 0.5},
        "loss": {"name": "ce"},
    },
    "sp_both": {
        "attn": {"name": "sp", "k": 256, "r_ratio": 0.5, "renorm": False},
        "ffn": {"name": "sp", "k_ratio": 0.08, "r_ratio": 0.5},
        "loss": {"name": "ce"},
    },
    "fast_sp": {
        "attn": {
            "name": "fast_sp",
            "window_size": 256,
            "chunk_size": 512,
            "flex_block_size": 128,
            "cable_augmented_dims": 8,
            "use_flex_attention": True,
        },
        "ffn": {
            "name": "fast_sp",
            "active_width": 128,
        },
        "loss": {"name": "ce"},
    },
    # Explicit name for the combined fast attention + fast FFN variant.
    # ``fast_sp`` above is kept unchanged as a backwards-compatible alias.
    "fast_sp_both": {
        "attn": {
            "name": "fast_sp",
            "window_size": 256,
            "chunk_size": 512,
            "flex_block_size": 128,
            "cable_augmented_dims": 8,
            "use_flex_attention": True,
        },
        "ffn": {
            "name": "fast_sp",
            "active_width": 128,
        },
        "loss": {"name": "ce"},
    },
}

data = {
    "corpus": "OWT",
    "hf_dataset": "Skylion007/openwebtext",
    "raw_alias": "OWT",
    "tokenizer_alias": "gpt2",
    "tokenized_alias": "OWT_gpt2",
    "blocks_alias": "OWT_gpt2_b1024_train125k",
    "block_size": 1024,
    "train_blocks": 125000,
    "valid_blocks": 2500,
    "seed": 42,
}

train = {
    # 2 x 1024 tokens per micro-batch, accumulated four times, preserves the
    # old task6 budget of 8192 training tokens per optimizer step.
    "batch_size": 2,
    "gradient_accumulation_steps": 4,
    "lr": 1e-4,
    "min_lr": 1e-5,
    "warmup_steps": 1000,
    "max_steps": 60000,
    "lr_schedule": "warmup_cosine",
    "grad_clip": 1.0,
    "log_interval": 1000,
    "eval_interval": 2500,
    "save_interval": 20000,
    "eval_batches": 20,
    "eval_seed": 42,
    "retrain": False,
}

benchmark = {
    "batch_size": 1,
    # 1024 matches training; 2048 is a block-only scaling probe and does not
    # require regenerating the tokenized training dataset.
    "context_lengths": [1024, 2048],
    "context_length": 1024,
    "layer": 1,
    "warmup_steps": 5,
    "measure_steps": 50,
    "repeats": 5,
    "seed": 2027,
}

sae = {
    "sae_alias": "topk",
    "hook_layer": -1,
    "layers": [6],
    "k": 32,
    "k_grid": [8, 16, 32, 64, 128],
    "expansion": 8,
    "expansion_grid": [8],
    "seed": [42],
    "lr": 1e-3,
    "max_steps": 3000,
    "gradient_accumulation_steps": 4,
    "log_interval": 100,
    "eval_batches": 20,
    "eval_seed": 9102,
    "data_seed": 404,
    "initialize_decoder_bias": True,
    "tied_init": True,
    "normalize_decoder": True,
    "aux_dead_loss_weight": 0.03125,
    "aux_k": 512,
    "dead_steps_threshold": 200,
    "rare_feature_threshold": 1e-5,
    "duplication_eval_features": 4096,
    "ablation_features": 16,
    "ablation_batches": 2,
    "retrain": True,
}

interpretability = {
    "enabled": True,
    "recompute": False,
    "eval_seed": 314159,
    "max_tokens": 32768,
    "encode_batch_size": 4096,
    "sae_selection": {
        "mode": "all",
        "layers": [6],
        "expansions": [8],
        "k_values": [8, 16, 32, 64, 128],
        "sae_seeds": [42],
    },
    "train_fraction": 0.6,
    "validation_fraction": 0.2,
    "concepts": {
        "enabled": True,
        "include_first_letter": True,
        "include_surface": True,
        "include_keyword_concepts": True,
        "min_positive_train": 64,
        "min_positive_test": 64,
        "max_concepts": None,
        "probe_feature_counts": [1, 2, 5, 10, 16],
        "primary_probe_budget": 5,
        "probe_regularization": [1e-4, 1e-3, 1e-2, 1e-1],
        "probe_steps": 250,
        "probe_lr": 0.05,
        "probe_validation_patience": 25,
        "random_projection_dim": 256,
        "keyword_concepts": {
            "pronoun": ["i", "you", "he", "she", "we", "they", "me", "him", "her", "us", "them"],
            "article": ["a", "an", "the"],
            "negation": ["no", "not", "never", "none", "without", "neither", "nor"],
            "positive_affect": ["good", "great", "excellent", "happy", "love", "wonderful", "best"],
            "negative_affect": ["bad", "awful", "terrible", "sad", "hate", "worst", "poor"],
            "calendar": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday", "january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december"],
            "code_keyword": ["def", "class", "import", "return", "function", "const", "var", "public", "private"],
        },
    },
    "fade": {
        "enabled": True,
        "mode": "annotation_backed",
        "features_per_concept": 1,
        "natural_samples_per_feature": 100,
        "top_activation_fraction": 0.25,
        "percentile_ranges": [[0.0, 0.5], [0.5, 0.75], [0.75, 0.95], [0.95, 1.0]],
        "synthetic_concept_samples": 50,
        "synthetic_nonconcept_samples": 50,
        "continuations_per_factor": 20,
        "modification_factors": [-2, -1, 0, 1, 2, 5, 10, 20, 50],
        "external_open_vocabulary": {
            "enabled": False,
            "package": "fade-language",
            "description_source": "max_activation",
            "explainer_backend": "openai_compatible",
            "explainer_model": None,
            "evaluator_backend": "openai_compatible",
            "evaluator_model": None,
            "api_base": None,
            "api_key_env": "FADE_API_KEY",
        },
    },
    "no_explanation": {
        "enabled": True,
        "sample_features": 256,
        "examples_per_feature": 20,
        "hard_negatives_per_feature": 20,
        "activation_frequency_bins": [0.0, 1e-5, 1e-4, 1e-3, 1e-2, 1.0],
        "export_contexts": True,
        "context_tokens": 16,
        # AP is prevalence-corrected before thresholding so broad concepts such
        # as ``alphabetic`` cannot explain every feature by default.
        "known_concept_auprc_gain_threshold": 0.05,
        "context_coherence_threshold": 0.55,
        "hard_negative_margin_threshold": 0.05,
    },
    "human_audit": {
        "enabled": True,
        "export_blinded_packets": True,
        "features_per_run": 100,
        "examples_per_feature": 10,
        "hard_negatives_per_feature": 10,
        "target_raters_per_item": 3,
        "rating_scale": [1, 2, 3, 4, 5],
        "annotation_file": None,
        "report_inter_rater_agreement": True,
    },
    "absorption": {
        "enabled": True,
        "parent_concepts": ["alphabetic", "numeric", "punctuation"],
        "candidate_features": 20,
        "max_selected_candidates": 5,
        "max_validation_fpr_increase": 0.02,
    },
    "causal": {
        "enabled": True,
        "feature_budgets": [1, 2, 5, 10],
        "strengths": [0.5, 1.0, 2.0],
        "max_concepts": 24,
        "max_batches": 2,
        "max_examples_per_concept": 512,
        "random_controls": 5,
        "isolation_kl_floor": 1e-4,
        "preserve_reconstruction_residual": True,
        "measure_kl_side_effect": True,
    },
    "stability": {
        "enabled": True,
        "matching": "hungarian",
        "max_features": 8192,
        "activation_tokens": 8192,
        "similarity_thresholds": [0.7, 0.8, 0.9],
        "frequency_bins": [0.0, 1e-5, 1e-4, 1e-3, 1e-2, 1.0],
        "correlation_chunk_size": 256,
        "max_parallel_jobs": 1,
    },
    "null_controls": {
        "permuted_latents": True,
        "random_projection": True,
        "random_feature_ablation": True,
        "untrained_sae": True,
        "random_transformer": True,
        "null_seed": 8675309,
        "probe_budget": 5,
    },
    "statistics": {
        "confidence": 0.95,
        "bootstrap_repeats": 2000,
        "fdr_alpha": 0.05,
        "paired_model_seeds": True,
        "hierarchical_bootstrap": True,
        "minimum_independent_model_seeds": 10,
        "primary_metrics": [
            "k_at_95_loss_recovered",
            "concept_macro_auprc",
            "causal_necessity_isolation",
            "stability_pw_mcc",
        ],
    },
}

attn = {
    "eval_batches": 20,
    "eval_seed": 424242,
}

ffn = {
    "eval_batches": 20,
    "eval_seed": 424242,
}

eval = {
    "baseline": "base",
    "primary_layer": 6,
    "primary_expansion": 8,
    "max_lm_loss_delta": 0.25,
    "max_sae_loss_delta": 0.0,
    "match_sae_l0": True,
    "match_loss_recovered": True,
    "loss_recovered_target": 0.95,
    "report_pareto_frontier": True,
}
